### ISSUE TITLE
Video bandwidth for two-way links in one window is stuck at 80 kbit/s

### ISSUE THREAD

**Issue by chrismarquardt** [steveseguin/obsninja#167] opened 2020-06-13 18:04 UTC
When using a two-way connection in one tab, &videobandwidth isn't observed.

Example: 
- side 1: https://obs.ninja/?push=p123&view=v123&videobandwidth=1000 
- side 2: https://obs.ninja/?push=v123&view=p123&videobandwidth=1000

Result:
Receiving tile on both sides is at 80 kbit/s

**Comment by jcalado** [comment] 2020-06-14 10:18
This is a feature, not a bug: 

> Bitrates of group chat videos are set to about 80kbps now. When videos are throttled in terms of bitrate, they also have their resolution scaled back now to reduce CPU load also. Limiting bitrate and resolution in the group chat allows for larger group sizes.

**Comment by steveseguin** [comment] 2020-06-14 17:48
In the upcoming release I've allowed bitrates to be manually changed to something other than 80kbps ONLY so long as you are not in a "room". If you are in a room though, my goal will be to have just the director of that room being able to control of bitrates.

I've also added a max-bitrate value, for the publisher, which limits the max bitrate remote peers can ask for.

**Comment by chrismarquardt** [comment] 2020-06-14 17:52
@jcalado I guess it's a special case with a 2-person "group" that's not really a group in a room. It's complicated :) Thanks @steveseguin for adding this.

**Comment by steveseguin** [comment] 2020-06-16 07:53
I've further modified the bitrates a bit for real group rooms; if there are just a couple people in a group room, the bit rates will be closer to ~200kbps each.  As more people join, the bitrate drops down. This will be part of the next release, pending the beta testing period goes well.

Anyways, closing the issue as the main request was addressed.

**Closed by steveseguin** 2020-06-16 07:53 UTC
